version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/xjl/workspace/athena-data/mysql/data:/var/lib/mysql
      - /home/xjl/workspace/athena-data/mysql/my.cnf:/etc/mysql/my.cnf
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/xjl/workspace/athena-data/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/xjl/workspace/athena-data/redis/data:/data
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "
