application:
  name: dev环境 @artifactId@
  version: dev环境 @version@
developer:
  name: dev环境 zhuangxiaoyan
  website: dev环境 http://zhuangxiaoyan.com
  qq: dev环境 2462612540-dev
  phone-number: dev环境 18279148786