application:
  name: prod环境 @artifactId@
  version: prod环境 @version@
developer:
  name: prod环境 zhuangxiaoyan
  website: prod环境 http://zhuangxiaoyan.com
  qq: prod环境 2462612540-prod
  phone-number: prod环境 18279148786