application:
  name: test环境 @artifactId@
  version: test环境 @version@
developer:
  name: test环境 xkcoding
  website: test环境 http://zhuangxiaoyan.com
  qq: test环境 2462612540-test
  phone-number: test环境 18279148786